In [ ]:
import pandas

In [1]:
import pandas
pandas.read_csv('mark.csv')

NameError: name 'pandas' is not defined

In [2]:
import pandas


In [4]:
db=pandas.read_csv('mark.csv')

In [5]:
db

name  hrs  marks
0  vimal    7     70
1  rahul    5     50
2   eric    8     80
3  harry    2     20

In [8]:
#target/dependent variable
y=db["marks"]


In [9]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [10]:
#feature/independent variable
x=db["hrs"]


In [11]:
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
mind = LinearRegression()

In [28]:
#exp:model:linear function
#w:weight/coefficient
mind.fit( x, y )

ValueError: Expected 2D array, got 1D array instead:
array=[7 5 8 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [27]:
x.shape

(4,)

In [16]:
x.reshape(4,1)

AttributeError: 'Series' object has no attribute 'reshape'

In [17]:
type(x)

pandas.core.series.Series

In [18]:
x.values

array([7, 5, 8, 2], dtype=int64)

In [19]:
x=x.values

In [20]:
type(x)

numpy.ndarray

In [21]:
x.reshape(4,1)

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [22]:
x.reshape(4,1).shape

(4, 1)

In [23]:
#model trained
mind.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[7 5 8 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [24]:
mind.fit( x , y  )

ValueError: Expected 2D array, got 1D array instead:
array=[7 5 8 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
mind = LinearRegression()

In [25]:
#model trained
mind.fit( x, y)

ValueError: Expected 2D array, got 1D array instead:
array=[7 5 8 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [29]:
x

array([7, 5, 8, 2], dtype=int64)

In [30]:
x = x.reshape(4,1)

In [31]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [32]:
mind.fit(  x, y)

LinearRegression()

In [33]:
mind.predict(6)

ValueError: Expected 2D array, got scalar array instead:
array=6.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [34]:
mind.predict([[6]])

array([60.])

In [35]:
#linear function :y=wx
#w=10
mind.coef_

array([10.])

In [36]:
import joblib

In [37]:
joblib.dump(mind,'mark.pk1')

['mark.pk1']

In [1]:
import pandas
from sklearn.linear_model import LinearRegression
db=pandas.read_csv('mark.csv')
y=db["marks"]
x=db["hrs"].values.reshape(4,1)
mind = LinearRegression()
mind.fit(  x, y)
mind.predict([[6]])


array([60.])

In [1]:
pwd

'C:\\Users\\rjosh\\machine learning model'